name:           codingame-hs
version:        1.2.0
license:        MIT
license-file:   LICENSE
homepage:       https://github.com/Chatanga/codingame-hs#readme
author:         Florent Lioult
maintainer:     florent@hihan.org
copyright:      2016 Florent Lioult
category:       Game
synopsis:       A simple library to play with the Codingame site.

dependencies:
- base
- aeson
- attoparsec
- bytestring
- containers
- filepath
- haskell-src-exts
- hpp
- HTTP
- http-client
- http-client-tls
- http-types
- mtl
- text
- transformers

library:
  source-dirs: src

tests:
  codingame-hs-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - codingame-hs
    - HUnit
    - test-framework
    - test-framework-hunit
